// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdalbratudtzpydnnnvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYWxicmF0dWR0enB5ZG5ubnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjYyODYsImV4cCI6MjA1ODQwMjI4Nn0.ESfN_ZCEvsPERZ1NCLKUV5HUKJ1vEUhYi6K3GLCmv94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);